language: android

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.1
    - android-24
    - extra-android-m2repository

before_script:
    - chmod +x gradlew

#Ignore the fabric step, since we do not have a legit API key for Fabric
script: "./gradlew build"
